#nullable enable
// =============================================================================
// Author: Vladyslav Zaiets | https://sarmkadan.com
// CTO & Software Architect
// =============================================================================

using System.Text;

namespace DotnetServiceScaffold.Infrastructure.DockerCompose;

/// <summary>
/// Builds Docker Compose YAML from <see cref="DockerComposeOptions"/>.
/// Generates a services block, named volumes, and an isolated bridge network.
/// Optional Caddy and Redis services can be included via the options.
/// </summary>
public sealed class DockerComposeGenerator : IDockerComposeGenerator
{
    private readonly ILogger<DockerComposeGenerator> _logger;

    public DockerComposeGenerator(ILogger<DockerComposeGenerator> logger)
    {
        _logger = logger;
    }

    /// <inheritdoc/>
    public string Generate(DockerComposeOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);

        _logger.LogInformation("Generating Docker Compose for service {ServiceName} (IncludeCaddy={IncludeCaddy}, IncludeRedis={IncludeRedis}, IncludePrometheus={IncludePrometheus})",
            options.ServiceName, options.IncludeCaddy, options.IncludeRedis, options.IncludePrometheus);

        var sb = new StringBuilder();

        AppendHeader(sb);
        sb.AppendLine("services:");
        AppendAppService(sb, options);

        if (options.IncludeCaddy)
        {
            AppendCaddyService(sb, options);
        }

        if (options.IncludeRedis)
        {
            AppendRedisService(sb, options);
        }

        AppendVolumes(sb, options);
        AppendNetworks(sb, options);

        if (options.IncludePrometheus)
        {
            AppendPrometheusComment(sb, options);
        }

        var result = sb.ToString();
        _logger.LogDebug(
            "Generated Docker Compose with {ServiceCount} service(s) for '{ServiceName}'",
            CountServices(options),
            options.ServiceName);

        _logger.LogInformation("Finished generating Docker Compose for service {ServiceName} with {ServiceCount} service(s)",
            options.ServiceName, CountServices(options));

        return result;
    }

    /// <inheritdoc/>
    public async Task WriteToFileAsync(
        DockerComposeOptions options,
        string outputPath,
        CancellationToken cancellationToken = default)
    {
        _logger.LogInformation("Writing Docker Compose file to {OutputPath} for service {ServiceName}", outputPath, options.ServiceName);
        try
        {
            var content = Generate(options);
            await File.WriteAllTextAsync(outputPath, content, Encoding.UTF8, cancellationToken);
            _logger.LogInformation("Docker Compose file written to {OutputPath}", outputPath);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to write Docker Compose file to {OutputPath}", outputPath);
            throw;
        }
    }

    private static void AppendHeader(StringBuilder sb)
    {
        sb.AppendLine("# Generated by dotnet-service-scaffold");
        sb.AppendLine("# Modify as needed for your deployment environment.");
        sb.AppendLine();
    }

    private static void AppendAppService(StringBuilder sb, DockerComposeOptions options)
    {
        sb.AppendLine($"  {options.ServiceName}:");
        sb.AppendLine($"    image: {options.ImageName}");
        sb.AppendLine($"    container_name: {options.ServiceName}");
        sb.AppendLine("    restart: unless-stopped");
        sb.AppendLine("    ports:");
        sb.AppendLine($"      - \"{options.HostPort}:{options.ContainerPort}\"");
        sb.AppendLine("    environment:");
        sb.AppendLine($"      ASPNETCORE_ENVIRONMENT: {options.Environment}");
        sb.AppendLine($"      ASPNETCORE_URLS: http://+:{options.ContainerPort}");
        sb.AppendLine($"      ConnectionStrings__DefaultConnection: {options.ConnectionString}");

        foreach (var (key, value) in options.EnvironmentVariables)
        {
            sb.AppendLine($"      {key}: {value}");
        }

        AppendServiceVolumes(sb, options);
        AppendHealthCheck(sb, options);
        AppendResourceLimits(sb, options);

        sb.AppendLine("    networks:");
        sb.AppendLine($"      - {options.ServiceName}-network");
        sb.AppendLine();
    }

    private static void AppendServiceVolumes(StringBuilder sb, DockerComposeOptions options)
    {
        if (options.Volumes.Count == 0)
        {
            return;
        }

        sb.AppendLine("    volumes:");
        foreach (var (volumeName, containerPath) in options.Volumes)
        {
            sb.AppendLine($"      - {volumeName}:{containerPath}");
        }
    }

    private static void AppendHealthCheck(StringBuilder sb, DockerComposeOptions options)
    {
        sb.AppendLine("    healthcheck:");
        sb.AppendLine($"      test: [\"CMD\", \"curl\", \"-f\", \"http://localhost:{options.ContainerPort}/health\"]");
        sb.AppendLine("      interval: 30s");
        sb.AppendLine("      timeout: 5s");
        sb.AppendLine("      retries: 3");
        sb.AppendLine("      start_period: 15s");
    }

    private static void AppendResourceLimits(StringBuilder sb, DockerComposeOptions options)
    {
        sb.AppendLine("    deploy:");
        sb.AppendLine("      resources:");
        sb.AppendLine("        limits:");
        sb.AppendLine($"          cpus: '{options.CpuLimit}'");
        sb.AppendLine($"          memory: {options.MemoryLimit}");
    }

    private static void AppendCaddyService(StringBuilder sb, DockerComposeOptions options)
    {
        var domain = string.IsNullOrWhiteSpace(options.CaddyDomain) ? "localhost" : options.CaddyDomain;

        sb.AppendLine("  caddy:");
        sb.AppendLine("    image: caddy:latest");
        sb.AppendLine("    container_name: caddy");
        sb.AppendLine("    restart: unless-stopped");
        sb.AppendLine("    ports:");
        sb.AppendLine("      - \"80:80\"");
        sb.AppendLine("      - \"443:443\"");
        sb.AppendLine("    environment:");
        sb.AppendLine($"      APP_DOMAIN: {domain}");
        sb.AppendLine($"      APP_UPSTREAM: {options.ServiceName}:{options.ContainerPort}");
        sb.AppendLine("    volumes:");
        sb.AppendLine("      - caddy-data:/data");
        sb.AppendLine("      - caddy-config:/config");
        sb.AppendLine("    networks:");
        sb.AppendLine($"      - {options.ServiceName}-network");
        sb.AppendLine("    depends_on:");
        sb.AppendLine($"      - {options.ServiceName}");
        sb.AppendLine();
    }

    private static void AppendRedisService(StringBuilder sb, DockerComposeOptions options)
    {
        sb.AppendLine("  redis:");
        sb.AppendLine("    image: redis:7-alpine");
        sb.AppendLine("    container_name: redis");
        sb.AppendLine("    restart: unless-stopped");
        sb.AppendLine("    expose:");
        sb.AppendLine("      - \"6379\"");
        sb.AppendLine("    volumes:");
        sb.AppendLine("      - redis-data:/data");
        sb.AppendLine("    healthcheck:");
        sb.AppendLine("      test: [\"CMD\", \"redis-cli\", \"ping\"]");
        sb.AppendLine("      interval: 10s");
        sb.AppendLine("      timeout: 3s");
        sb.AppendLine("      retries: 3");
        sb.AppendLine("    networks:");
        sb.AppendLine($"      - {options.ServiceName}-network");
        sb.AppendLine();
    }

    private static void AppendVolumes(StringBuilder sb, DockerComposeOptions options)
    {
        sb.AppendLine("volumes:");
        foreach (var volumeName in options.Volumes.Keys)
        {
            sb.AppendLine($"  {volumeName}:");
            sb.AppendLine("    driver: local");
        }

        if (options.IncludeCaddy)
        {
            sb.AppendLine("  caddy-data:");
            sb.AppendLine("    driver: local");
            sb.AppendLine("  caddy-config:");
            sb.AppendLine("    driver: local");
        }

        if (options.IncludeRedis)
        {
            sb.AppendLine("  redis-data:");
            sb.AppendLine("    driver: local");
        }

        sb.AppendLine();
    }

    private static void AppendNetworks(StringBuilder sb, DockerComposeOptions options)
    {
        sb.AppendLine("networks:");
        sb.AppendLine($"  {options.ServiceName}-network:");
        sb.AppendLine("    driver: bridge");
        sb.AppendLine();
    }

    private static void AppendPrometheusComment(StringBuilder sb, DockerComposeOptions options)
    {
        sb.AppendLine("# Prometheus scrape configuration (add to prometheus.yml):");
        sb.AppendLine("# scrape_configs:");
        sb.AppendLine($"#   - job_name: '{options.ServiceName}'");
        sb.AppendLine("#     static_configs:");
        sb.AppendLine($"#       - targets: ['{options.ServiceName}:{options.ContainerPort}']");
        sb.AppendLine("#     metrics_path: /metrics");
    }

    private static int CountServices(DockerComposeOptions options)
    {
        var count = 1;

        if (options.IncludeCaddy)
        {
            count++;
        }

        if (options.IncludeRedis)
        {
            count++;
        }

        return count;
    }
}
